services:
  - type: web
    name: sunshine-node-link
    runtime: image
    image:
      url: docker.io/bacontheoverseer/sunshine-learning:latest # Pulls directly from your Docker Hub
    plan: free
    region: oregon # Fast default region
    envVars:
      - key: PORT
        value: 3000
