services:
  - type: web
    name: sunshine-node-link
    env: docker
    repo: https://github.com/bacontheoverseer/SunshineNord-deployer # Link to THIS github repo
    plan: free
    region: oregon # Fast default region
    dockerconfig:
      dockerImage: bacontheoverseer/sunshine-learning:latest # Pulls your compiled image from Step 1
    envVars:
      - key: PORT
        value: 3000
